name: Auto Review

on:
  pull_request:
    types: [opened]

permissions:
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: "APPROVE",
              body: "Auto review ✅"
            });
